Feature/canvas android
Vizzuality/react-native-maps pull request #5
Opened 2017-05-26 11:55 UTC by j8seangel

This PR includes the custom Canvas Android implementation what adds the below features:
- Offline support,
- Custom canvas filter by dates layer.
- New interaction layer to highlight the area selected (TODO: improve the highlight size in zoom level changes)

This component extends the UrlTile one and receives the following new params:
- areaId: necessary to generate the cached folder.
- alertType: supports VIIRS("viirs") and GLAD ("umd_as_it_happens") layers, also mandatory for the cached folder.
- isConnected: gets the online status in the app to get from the server or from the cached folder
- min and maxDate: dates with the days count from the origin in GLAD('20150101') and 1(today)-8(last-week) to VIIRS.

2017-05-26 11:58 UTC, j8seangel commented
Please, don't merge until the master branch is sync with the airbnb master branch to keep the repos synched and make the conflicts easier to solve.
Also remember to remove `#feature/canvas-android` from the FW repo package.json in `"react-native-maps": "Vizzuality/react-native-maps#feature/canvas-android"`

2017-05-26 12:07 UTC, j8seangel commented
Feel free to merge!

2017-05-29 10:05 UTC, sorodrigo requested changes
Great! I left you some marks on some logs I found.

2017-05-29 10:05 UTC, sorodrigo commented on lib/android/src/main/java/com/airbnb/android/react/maps/AirMapCanvasInteractionUrlTileManager.java
> +        Log.d("Map", "Get name");
is this a console log?

2017-05-29 10:05 UTC, sorodrigo commented on example/examples/CustomTiles.js
> +    console.log(coordinates);
console log

2017-05-29 10:05 UTC, sorodrigo commented on lib/android/src/main/java/com/airbnb/android/react/maps/AirMapCanvasUrlTileManager.java
> +        Log.d("Map", "Get name");
log

2017-05-29 10:05 UTC, sorodrigo commented on lib/android/src/main/java/com/airbnb/android/react/maps/AirMapCanvasTileProvider.java
> +            Log.d("tile Position: ", x + "-" + y + "-" + zoom);
log

2017-05-29 10:37 UTC, j8seangel commented
Logs removed

2017-05-29 10:38 UTC, sorodrigo approved these changes

2017-05-29 10:38 UTC, merged

2017-05-29 11:05 UTC, geriux commented
Awesome work!!!!!!